[env]
TERM = "xterm-256color"

[window]
opacity = 0.95

[font]
size = 14.0

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[font.normal]
family = "SauceCodeProNerdFont"
style = "Regular"

[font.bold]
family = "SauceCodeProNerdFont"
style = "Bold"

[font.italic]
family = "SauceCodeProNerdFont"
style = "it"

[font.bold_italic]
family = "SauceCodeProNerdFont"
style = "Boldit"

[colors.selection]
background = "0x003300"
text = "0x00ff00"

[colors.primary]
background = "0x17191a"
bright_foreground = "0xffffff"
dim_foreground = "0x9a9a9a"
foreground = "0xebdbb2"

[colors.normal]
black = "0x282828"
blue = "0x508a8d"
cyan = "0x689d6a"
green = "0xb5bd68"
magenta = "0xb16286"
red = "0xcc241d"
white = "0xa89984"
yellow = "0xd79921"

[colors.bright]
black = "0x928374"
blue = "0x8fb1a4"
cyan = "0x9fd18c"
green = "0xc5dc85"
magenta = "0xe799ae"
red = "0xfb4934"
white = "0xebdbb2"
yellow = "0xfbbe30"
